// frontend/src/components/results/InvoiceDrawer.tsx
import { Alert, App, Button, Descriptions, Drawer, List, Space, Table, Tabs, Tag, Typography } from "../../app/antd";
import { useCallback, useEffect, useState } from "react";

import {
  createInvoiceRetry,
  getErrorMessage,
  getInvoiceDetail,
  getInvoicePreviewUrl,
  getInvoiceOriginalPreviewUrl,
} from "../../app/api";
import type { ExtractedField, FieldCheck, InvoiceDetail, InvoiceSummary } from "../../app/types";
import { AsyncBoundary } from "../common/AsyncBoundary";
import { ReviewActions } from "./ReviewActions";
import {
  getResultStatusColor,
  getResultStatusLabel,
  getReviewStatusColor,
  getReviewStatusLabel,
} from "./resultPresentation";


interface InvoiceDrawerProps {
  invoiceId: string | null;
  open: boolean;
  onClose: () => void;
  onChanged: () => Promise<void> | void;
}

const extractedFieldColumns = [
  {
    title: "字段",
    dataIndex: "field_name",
    key: "field_name",
    width: 140,
  },
  {
    title: "提取值",
    dataIndex: "normalized_value",
    key: "normalized_value",
    render: (_: string | null, record: ExtractedField) => record.normalized_value || record.extracted_value || "--",
  },
  {
    title: "置信度",
    dataIndex: "confidence",
    key: "confidence",
    width: 100,
    render: (value: string | null) => value || "--",
  },
  {
    title: "来源片段",
    dataIndex: "source_fragment",
    key: "source_fragment",
    ellipsis: true,
  },
];

const fieldCheckColumns = [
  {
    title: "校验项",
    dataIndex: "field_name",
    key: "field_name",
    width: 160,
  },
  {
    title: "期望值",
    dataIndex: "expected_value",
    key: "expected_value",
  },
  {
    title: "实际值",
    dataIndex: "actual_value",
    key: "actual_value",
  },
  {
    title: "结果",
    dataIndex: "match_result",
    key: "match_result",
    width: 120,
  },
  {
    title: "原因",
    dataIndex: "reason",
    key: "reason",
    ellipsis: true,
  },
];

function renderStatusTag(status: string) {
  return <Tag color={getResultStatusColor(status)}>{getResultStatusLabel(status)}</Tag>;
}

function getEvidenceSourceLabel(sourceType: string | null | undefined): string {
  if (sourceType === "ocr") {
    return "图片识别";
  }
  if (sourceType === "text") {
    return "文本提取";
  }
  if (sourceType === "pdf") {
    return "PDF 解析";
  }
  return "识别片段";
}

export function InvoiceDrawer({ invoiceId, open, onClose, onChanged }: InvoiceDrawerProps) {
  const { message } = App.useApp();
  const [invoice, setInvoice] = useState<InvoiceDetail | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [retrying, setRetrying] = useState(false);

  const loadInvoice = useCallback(async () => {
    if (!invoiceId) {
      setInvoice(null);
      setError(null);
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const detail = await getInvoiceDetail(invoiceId);
      setInvoice(detail);
    } catch (nextError) {
      setError(getErrorMessage(nextError));
    } finally {
      setLoading(false);
    }
  }, [invoiceId]);

  useEffect(() => {
    if (open && invoiceId) {
      void loadInvoice();
    }
  }, [invoiceId, loadInvoice, open]);

  return (
    <Drawer width={960} open={open} onClose={onClose} title="发票详情" destroyOnClose>
      <AsyncBoundary loading={loading} error={error}>
        {invoice ? (
          <div className="drawer-body">
            <Space wrap className="status-row">
              {renderStatusTag(invoice.display_status)}
              <Tag
                color={getReviewStatusColor({
                  processingStatus: invoice.processing_status,
                  systemDecision: invoice.system_decision,
                  duplicateFlag: invoice.duplicate_flag,
                  reviewStatus: invoice.review_status,
                })}
              >
                {getReviewStatusLabel({
                  processingStatus: invoice.processing_status,
                  systemDecision: invoice.system_decision,
                  duplicateFlag: invoice.duplicate_flag,
                  reviewStatus: invoice.review_status,
                })}
              </Tag>
            </Space>
            <Descriptions bordered size="small" column={2} className="description-block">
              <Descriptions.Item label="原文件名">{invoice.original_filename}</Descriptions.Item>
              <Descriptions.Item label="新文件名">{invoice.renamed_filename || "未重命名"}</Descriptions.Item>
              <Descriptions.Item label="金额">{invoice.invoice_amount || "--"}</Descriptions.Item>
              <Descriptions.Item label="日期">{invoice.invoice_date || "--"}</Descriptions.Item>
              <Descriptions.Item label="购方名称">{invoice.buyer_name || "--"}</Descriptions.Item>
              <Descriptions.Item label="购方税号">{invoice.buyer_tax_no || "--"}</Descriptions.Item>
              <Descriptions.Item label="发票号码">{invoice.invoice_number || "--"}</Descriptions.Item>
              <Descriptions.Item label="问题数">{invoice.problem_count}</Descriptions.Item>
            </Descriptions>
            <Descriptions bordered size="small" column={1} className="description-block">
              <Descriptions.Item label="处理结论">{getResultStatusLabel(invoice.display_status)}</Descriptions.Item>
              <Descriptions.Item
                label="人工确认"
              >
                {getReviewStatusLabel({
                  processingStatus: invoice.processing_status,
                  systemDecision: invoice.system_decision,
                  duplicateFlag: invoice.duplicate_flag,
                  reviewStatus: invoice.review_status,
                })}
              </Descriptions.Item>
              <Descriptions.Item label="建议动作">
                {invoice.suggested_actions.length > 0 ? invoice.suggested_actions.join("，") : "--"}
              </Descriptions.Item>
              <Descriptions.Item label="结论原因">
                {invoice.decision_reasons.length > 0 ? invoice.decision_reasons.join("，") : "--"}
              </Descriptions.Item>
            </Descriptions>
            {(invoice.attachments ?? []).length > 0 ? (
              <List
                header="清单附件识别"
                bordered
                className="description-block"
                dataSource={invoice.attachments}
                renderItem={(item) => (
                  <List.Item>
                    <Space direction="vertical" size={2} className="full-width">
                      <Space wrap>
                        <Typography.Text strong>{item.original_filename}</Typography.Text>
                        <Tag>{item.attachment_status_label}</Tag>
                      </Space>
                      <Typography.Text type="secondary">{item.match_reason || "无匹配依据"}</Typography.Text>
                    </Space>
                  </List.Item>
                )}
              />
            ) : null}
            {invoice.retryable ? (
              <Space>
                <Button
                  onClick={async () => {
                    setRetrying(true);
                    try {
                      await createInvoiceRetry({ invoiceId: invoice.id });
                      message.success("当前票已重新入队");
                      await loadInvoice();
                      await onChanged();
                    } catch (nextError) {
                      message.error(getErrorMessage(nextError));
                    } finally {
                      setRetrying(false);
                    }
                  }}
                  loading={retrying}
                >
                  重试当前票
                </Button>
              </Space>
            ) : null}
            <Tabs
              items={[
                {
                  key: "preview",
                  label: "PDF 预览",
                  children: (
                    <Space direction="vertical" size="middle" className="full-width">
                      <Space>
                        <Button onClick={() => window.open(getInvoiceOriginalPreviewUrl(invoice.id), "_blank", "noopener,noreferrer")}>
                          打开原始 PDF
                        </Button>
                      </Space>
                      <div className="preview-frame">
                        {invoice.preview_path ? (
                          <iframe src={getInvoicePreviewUrl(invoice.id)} title={invoice.original_filename} className="pdf-preview" />
                        ) : (
                          <Alert type="warning" showIcon message="当前记录没有可预览的文件路径" />
                        )}
                      </div>
                    </Space>
                  ),
                },
                {
                  key: "evidence",
                  label: "识别字段",
                  children: (
                    <Space direction="vertical" size="large" className="full-width">
                      <Table
                        rowKey="id"
                        columns={extractedFieldColumns}
                        dataSource={invoice.extracted_fields}
                        size="small"
                        pagination={false}
                      />
                      <List
                        header="证据片段"
                        bordered
                        dataSource={invoice.evidence_items}
                        renderItem={(item) => (
                          <List.Item>
                            <Space direction="vertical" size={4} className="full-width">
                              <Typography.Text strong>{`识别来源：${getEvidenceSourceLabel(item.source_type)}`}</Typography.Text>
                              <Typography.Paragraph className="evidence-text" ellipsis={{ rows: 4, expandable: true }}>
                                {item.raw_text || "无原始文本"}
                              </Typography.Paragraph>
                            </Space>
                          </List.Item>
                        )}
                      />
                    </Space>
                  ),
                },
                {
                  key: "rules",
                  label: "校验依据",
                  children: (
                    <Space direction="vertical" size="large" className="full-width">
                      <Descriptions bordered size="small" column={2}>
                        <Descriptions.Item label="基础校验">{invoice.basic_compliance_status || "--"}</Descriptions.Item>
                        <Descriptions.Item label="业务风险分类">{invoice.business_compliance_status || "--"}</Descriptions.Item>
                      </Descriptions>
                      <Table
                        rowKey="id"
                        columns={fieldCheckColumns}
                        dataSource={invoice.field_checks}
                        size="small"
                        pagination={false}
                      />
                    </Space>
                  ),
                },
                {
                  key: "advanced",
                  label: "高级诊断",
                  children: (
                    <Descriptions bordered size="small" column={2}>
                      <Descriptions.Item label="解析来源">{invoice.parse_source || "--"}</Descriptions.Item>
                      <Descriptions.Item label="失败阶段">{invoice.last_error_stage || "--"}</Descriptions.Item>
                      <Descriptions.Item label="错误码">{invoice.last_error_code || "--"}</Descriptions.Item>
                      <Descriptions.Item label="可重试">{invoice.retryable ? "是" : "否"}</Descriptions.Item>
                      <Descriptions.Item label="Provider">{invoice.provider_diagnostic.provider_name || "--"}</Descriptions.Item>
                      <Descriptions.Item label="Provider 版本">{invoice.provider_diagnostic.provider_version || "--"}</Descriptions.Item>
                      <Descriptions.Item label="Provider 错误">{invoice.provider_diagnostic.provider_error_code || "--"}</Descriptions.Item>
                      <Descriptions.Item label="失败信息">{invoice.last_error_message || invoice.failure_reason || "--"}</Descriptions.Item>
                      <Descriptions.Item label="系统标记">
                        {invoice.risk_flags.length > 0 ? invoice.risk_flags.join("，") : "--"}
                      </Descriptions.Item>
                      <Descriptions.Item label="重复识别键">{invoice.duplicate_group_key || "--"}</Descriptions.Item>
                    </Descriptions>
                  ),
                },
                {
                  key: "review",
                  label: "人工确认",
                  children: (
                    <Space direction="vertical" size="large" className="full-width">
                      <ReviewActions
                        invoiceId={invoice.id}
                        processingStatus={invoice.processing_status}
                        systemDecision={invoice.system_decision}
                        duplicateFlag={invoice.duplicate_flag}
                        reviewStatus={invoice.review_status}
                        onSubmitted={async (updatedInvoice: InvoiceSummary) => {
                          setInvoice((current) =>
                            current && current.id === updatedInvoice.id
                              ? {
                                  ...current,
                                  ...updatedInvoice,
                                }
                              : current,
                          );
                          await onChanged();
                          await loadInvoice();
                        }}
                      />
                      <List
                        header="确认留痕"
                        bordered
                        dataSource={invoice.review_actions}
                        locale={{ emptyText: "暂无人工确认记录" }}
                        renderItem={(item) => (
                          <List.Item>
                            <Space direction="vertical" size={2}>
                              <Typography.Text strong>{item.review_action}</Typography.Text>
                              <Typography.Text type="secondary">{`${item.reviewed_by} · ${item.reviewed_at}`}</Typography.Text>
                              {item.review_note ? <Typography.Text>{item.review_note}</Typography.Text> : null}
                            </Space>
                          </List.Item>
                        )}
                      />
                    </Space>
                  ),
                },
              ]}
            />
          </div>
        ) : null}
      </AsyncBoundary>
    </Drawer>
  );
}

// frontend/src/components/results/InvoiceDrawer.vue
<template>
  <div v-if="open" class="drawer-backdrop" role="presentation" @click.self="$emit('close')">
    <aside class="invoice-drawer" role="dialog" aria-modal="true" aria-label="发票详情">
      <div class="drawer-header">
        <h2>发票详情</h2>
        <AppButton label="关闭" variant="secondary" @click="$emit('close')" />
      </div>
      <AppAsyncBoundary :loading="loading" :error="error">
        <div v-if="invoice" class="drawer-body">
          <div class="status-row">
            <AppStatusTag
              :label="getStatusLabel(getResultBucket(invoice))"
              :severity="getStatusSeverity(getResultBucket(invoice))"
            />
            <AppStatusTag :label="getReviewLabel(invoice)" severity="info" />
          </div>

          <div class="detail-grid">
            <div><strong>原文件名</strong><span>{{ invoice.original_filename }}</span></div>
            <div><strong>建议新文件名</strong><span>{{ invoice.renamed_filename || "未重命名" }}</span></div>
            <div><strong>金额</strong><span>{{ invoice.invoice_amount || "--" }}</span></div>
            <div><strong>日期</strong><span>{{ invoice.invoice_date || "--" }}</span></div>
            <div><strong>购方名称</strong><span>{{ invoice.buyer_name || "--" }}</span></div>
            <div><strong>购方税号</strong><span>{{ invoice.buyer_tax_no || "--" }}</span></div>
          </div>

          <div class="tabs">
            <button
              v-for="tab in tabs"
              :key="tab.key"
              type="button"
              :class="{ active: activeTab === tab.key }"
              @click="activeTab = tab.key"
            >
              {{ tab.label }}
            </button>
          </div>

          <section v-if="activeTab === 'preview'" class="tab-panel">
            <AppButton label="打开原始 PDF" variant="secondary" @click="openOriginalPreview" />
            <div class="preview-frame">
              <iframe
                v-if="invoice.preview_path"
                class="pdf-preview"
                :src="getInvoicePreviewUrl(invoice.id)"
                :title="invoice.original_filename"
              />
              <AppMessage v-else severity="warn">当前记录没有可预览的文件路径。</AppMessage>
            </div>
          </section>

          <section v-else-if="activeTab === 'evidence'" class="tab-panel">
            <div class="responsive-table">
              <table>
                <thead>
                  <tr><th>字段</th><th>提取值</th><th>置信度</th><th>来源片段</th></tr>
                </thead>
                <tbody>
                  <tr v-for="field in invoice.extracted_fields" :key="field.id">
                    <td>{{ field.field_name }}</td>
                    <td>{{ field.normalized_value || field.extracted_value || "--" }}</td>
                    <td>{{ field.confidence || "--" }}</td>
                    <td>{{ field.source_fragment || "--" }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <section v-else-if="activeTab === 'rules'" class="tab-panel">
            <div class="detail-grid">
              <div><strong>基础校验</strong><span>{{ invoice.basic_compliance_status || "--" }}</span></div>
              <div><strong>业务风险分类</strong><span>{{ invoice.business_compliance_status || "--" }}</span></div>
            </div>
          </section>

          <section v-else-if="activeTab === 'review'" class="tab-panel">
            <ReviewActions :invoice="invoice" @submitted="handleReviewSubmitted" />
            <ul class="audit-list">
              <li v-for="item in invoice.review_actions" :key="item.id">
                <strong>{{ item.review_action }}</strong>
                <span>{{ item.reviewed_by }} · {{ item.reviewed_at }}</span>
                <p v-if="item.review_note">{{ item.review_note }}</p>
              </li>
            </ul>
          </section>

          <section v-else class="tab-panel">
            <div class="detail-grid">
              <div><strong>解析来源</strong><span>{{ invoice.parse_source || "--" }}</span></div>
              <div><strong>失败阶段</strong><span>{{ invoice.last_error_stage || "--" }}</span></div>
              <div><strong>错误码</strong><span>{{ invoice.last_error_code || "--" }}</span></div>
              <div><strong>Provider</strong><span>{{ invoice.provider_diagnostic.provider_name || "--" }}</span></div>
            </div>
          </section>
        </div>
      </AppAsyncBoundary>
    </aside>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";

import {
  getErrorMessage,
  getInvoiceDetail,
  getInvoiceOriginalPreviewUrl,
  getInvoicePreviewUrl,
} from "../../app/api";
import type { InvoiceDetail, InvoiceSummary } from "../../app/types";
import {
  getResultBucket,
  getReviewLabel,
  getStatusLabel,
  getStatusSeverity,
} from "../../domain/presentation";
import AppAsyncBoundary from "../../ui-adapter/AppAsyncBoundary.vue";
import AppButton from "../../ui-adapter/AppButton.vue";
import AppMessage from "../../ui-adapter/AppMessage.vue";
import AppStatusTag from "../../ui-adapter/AppStatusTag.vue";
import ReviewActions from "./ReviewActions.vue";

const props = defineProps<{
  invoiceId: string | null;
  open: boolean;
}>();

const emit = defineEmits<{
  close: [];
  changed: [];
}>();

const tabs = [
  { key: "preview", label: "PDF 预览" },
  { key: "evidence", label: "识别字段" },
  { key: "rules", label: "校验依据" },
  { key: "review", label: "人工确认" },
  { key: "advanced", label: "高级诊断" },
];
const invoice = ref<InvoiceDetail | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);
const activeTab = ref("preview");

async function loadInvoice() {
  if (!props.invoiceId) {
    invoice.value = null;
    return;
  }
  loading.value = true;
  error.value = null;
  try {
    invoice.value = await getInvoiceDetail(props.invoiceId);
  } catch (loadError) {
    error.value = getErrorMessage(loadError);
  } finally {
    loading.value = false;
  }
}

function openOriginalPreview() {
  if (invoice.value) {
    window.open(getInvoiceOriginalPreviewUrl(invoice.value.id), "_blank", "noopener,noreferrer");
  }
}

async function handleReviewSubmitted(updated: InvoiceSummary) {
  if (invoice.value && invoice.value.id === updated.id) {
    invoice.value = { ...invoice.value, ...updated };
  }
  emit("changed");
  await loadInvoice();
}

watch(
  () => [props.invoiceId, props.open] as const,
  () => {
    if (props.open && props.invoiceId) {
      activeTab.value = "preview";
      void loadInvoice();
    }
  },
);
</script>
