// frontend/src/components/results/ReviewActions.tsx
import { App, Button, Form, Input, Select, Space, Typography } from "../../app/antd";
import { useEffect, useState } from "react";

import { createReviewAction, getErrorMessage } from "../../app/api";
import { useOperatorSettings } from "../../app/operator-settings";
import type { InvoiceSummary } from "../../app/types";
import { getReviewStatusLabel, requiresManualReview } from "./resultPresentation";


interface ReviewActionsProps {
  invoiceId: string;
  processingStatus: string | null;
  systemDecision: string | null;
  duplicateFlag: boolean;
  reviewStatus: string | null;
  onSubmitted: (invoice: InvoiceSummary) => Promise<void> | void;
}

interface ReviewFormValues {
  reviewAction: string;
  reviewNote?: string;
}

const ACTION_OPTIONS = [
  { label: "确认通过", value: "approve" },
  { label: "确认驳回", value: "reject" },
  { label: "暂不处理", value: "keep_review_required" },
];

export function ReviewActions({
  invoiceId,
  processingStatus,
  systemDecision,
  duplicateFlag,
  reviewStatus,
  onSubmitted,
}: ReviewActionsProps) {
  const { message } = App.useApp();
  const { defaultOperatorName } = useOperatorSettings();
  const [form] = Form.useForm<ReviewFormValues>();
  const [submitting, setSubmitting] = useState(false);
  const reviewable = requiresManualReview({
    processingStatus,
    systemDecision,
    duplicateFlag,
    reviewStatus,
  });

  useEffect(() => {
    form.setFieldValue("reviewAction", "approve");
  }, [form]);

  if (!reviewable) {
    return (
      <Typography.Text type="secondary">
        {`当前票据${getReviewStatusLabel({
          processingStatus,
          systemDecision,
          duplicateFlag,
          reviewStatus,
        })}。`}
      </Typography.Text>
    );
  }

  const handleSubmit = async (values: ReviewFormValues) => {
    setSubmitting(true);
    try {
      const result = await createReviewAction({
        invoiceId,
        reviewAction: values.reviewAction,
        reviewNote: values.reviewNote,
      });
      message.success("人工确认已记录，结果会自动刷新。");
      form.setFieldValue("reviewNote", "");
      await onSubmitted(result.invoice);
    } catch (error) {
      message.error(getErrorMessage(error));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Form form={form} layout="vertical" onFinish={handleSubmit}>
      <Typography.Text type="secondary">{`当前操作者：${defaultOperatorName}`}</Typography.Text>
      <Form.Item<ReviewFormValues> label="处理动作" name="reviewAction" rules={[{ required: true, message: "请选择处理动作" }]}>
        <Select options={ACTION_OPTIONS} />
      </Form.Item>
      <Form.Item<ReviewFormValues> label="备注" name="reviewNote">
        <Input.TextArea rows={4} placeholder="记录人工确认依据" />
      </Form.Item>
      <Typography.Text type="secondary">提交后会立即刷新当前票据和批次结果。</Typography.Text>
      <Space>
        <Button type="primary" htmlType="submit" loading={submitting}>
          提交确认
        </Button>
      </Space>
    </Form>
  );
}

// frontend/src/components/results/ReviewActions.vue
<template>
  <form class="review-actions" @submit.prevent="submit">
    <label>
      人工确认动作
      <select v-model="reviewAction" :disabled="!reviewable || saving">
        <option value="approve">确认通过</option>
        <option value="reject">确认驳回</option>
        <option value="keep_review_required">暂不处理</option>
      </select>
    </label>
    <label>
      确认说明
      <textarea v-model.trim="reviewNote" :disabled="!reviewable || saving" maxlength="200" />
    </label>
    <AppButton label="提交人工确认" :loading="saving" :disabled="!reviewable" @click="submit" />
    <p v-if="!reviewable" class="muted">当前发票不需要人工确认。</p>
    <p v-if="notice" class="form-notice">{{ notice }}</p>
  </form>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

import { createReviewAction, getErrorMessage } from "../../app/api";
import type { InvoiceSummary } from "../../app/types";
import { getResultBucket, isInvoiceProcessing } from "../../domain/presentation";
import AppButton from "../../ui-adapter/AppButton.vue";

const props = defineProps<{
  invoice: InvoiceSummary;
}>();

const emit = defineEmits<{
  submitted: [invoice: InvoiceSummary];
}>();

const reviewAction = ref("approve");
const reviewNote = ref("");
const saving = ref(false);
const notice = ref("");
const reviewable = computed(() => {
  if (isInvoiceProcessing(props.invoice.processing_status)) {
    return false;
  }
  const bucket = getResultBucket(props.invoice);
  return bucket === "review_required" || bucket === "duplicate_in_batch";
});

async function submit() {
  if (!reviewable.value || saving.value) {
    return;
  }
  saving.value = true;
  notice.value = "";
  try {
    const result = await createReviewAction({
      invoiceId: props.invoice.id,
      reviewAction: reviewAction.value,
      reviewNote: reviewNote.value || undefined,
    });
    notice.value = "人工确认已提交。";
    emit("submitted", result.invoice);
  } catch (error) {
    notice.value = getErrorMessage(error);
  } finally {
    saving.value = false;
  }
}
</script>
